version: 0.2

env:
  parameter-store:
    FOSSA_API_KEY: "/CodeBuild/FOSSA_API_KEY"

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - bash run_fossa.sh
artifacts:
  files:
    - target/messageUtil-1.0.jar